name: Release to PyPi

on:
  push:
    branches: [ "master" ]

jobs:
  release_to_pypi:
    runs-on: ubuntu-latest
    name: release latest dist to py
    steps:
      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}